package com.minhtu.firesocialmedia.constants

class TestTag {
    companion object{
        const val TAG_USERNAME: String = "TAG_USERNAME"
        const val TAG_PASSWORD: String = "TAG_PASSWORD"
        const val TAG_CONFIRMPASSWORD: String = "TAG_CONFIRMPASSWORD"
        const val TAG_FORGOTPASSWORD: String = "TAG_FORGOTPASSWORD"
        const val TAG_REMEMBERPASSWORD: String = "TAG_REMEMBERPASSWORD"
        const val TAG_BUTTON_SIGNIN: String = "TAG_BUTTON_SIGNIN"
        const val TAG_BUTTON_SIGNUP: String = "TAG_BUTTON_SIGNUP"
        const val TAG_BUTTON_SIGNINGOOGLE: String = "TAG_BUTTON_SIGNINGOOGLE"
        const val TAG_BUTTON_BACK: String = "TAG_BUTTON_BACK"
        const val TAG_SELECT_AVATAR: String = "TAG_SELECT_AVATAR"
        const val TAG_SELECT_NAME: String = "TAG_SELECT_NAME"
        const val TAG_BUTTON_NEXT: String = "TAG_BUTTON_NEXT"
        const val TAG_ICON_BUTTON_SEARCH: String = "TAG_ICON_BUTTON_SEARCH"
        const val TAG_ICON_BUTTON_LOGOUT: String = "TAG_ICON_BUTTON_LOGOUT"
        const val TAG_BUTTON_LOGOUT: String = "TAG_BUTTON_LOGOUT"
        const val TAG_CURRENT_USER: String = "TAG_CURRENT_USER"
        const val TAG_CREATE_POST: String = "TAG_CREATE_POST"
        const val TAG_USERS_ROW: String = "TAG_USERS_ROW"
        const val TAG_ITEM_IN_ROW: String = "TAG_ITEM_IN_ROW"
        const val TAG_POSTS_COLUMN: String = "TAG_POST_COLUMN"
        const val TAG_POST_IN_COLUMN: String = "TAG_POST_IN_COLUMN"
        const val TAG_POSTER_AVATAR: String = "TAG_POSTER_AVATAR"
        const val TAG_POST_IMAGE: String = "TAG_POST_IMAGE"
        const val TAG_BUTTON_LIKE: String = "TAG_BUTTON_LIKE"
        const val TAG_BUTTON_COMMENT: String = "TAG_BUTTON_COMMENT"
        const val TAG_COMMENTS_LIST: String = "TAG_COMMENTS_LIST"
        const val TAG_INPUT_COMMENT: String = "TAG_INPUT_COMMENT"
        const val TAG_BUTTON_SEND: String = "TAG_BUTTON_SEND"
        const val COMMENT_CARD: String = "COMMENT_CARD"
        const val TAG_BUTTON_ADDFRIEND: String = "TAG_BUTTON_ADDFRIEND"
        const val TAG_BUTTON_MOREOPTIONS: String = "TAG_BUTTON_MOREOPTIONS"
        const val TAG_COVER_PHOTO: String = "TAG_COVER_PHOTO"
        const val TAG_USER_AVATAR: String = "TAG_USER_AVATAR"
        const val TAG_POST_MESSAGE: String = "TAG_POST_MESSAGE"
        const val TAG_BUTTON_SELECTIMAGE: String = "TAG_BUTTON_SELECTIMAGE"
        const val TAG_BUTTON_DELETE: String = "TAG_BUTTON_DELETE"
        const val TAG_BUTTON_POST: String = "TAG_BUTTON_POST"
        const val TAG_BUTTON_YES: String = "TAG_BUTTON_YES"
        const val TAG_BUTTON_NO: String = "TAG_BUTTON_NO"
        const val TAG_SEARCH_BAR: String = "TAG_SEARCH_BAR"
        const val TAG_FRIEND_TAB_LIST: String = "TAG_FRIEND_TAB_LIST"
        const val TAG_FRIEND: String = "TAG_FRIEND"
        const val TAG_FRIEND_REQUEST_TAB_LIST: String = "TAG_FRIEND_REQUEST_TAB_LIST"
        const val TAG_FRIEND_REQUEST: String = "TAG_FRIEND_REQUEST"
        const val TAG_NOTIFICATION_LIST: String = "TAG_NOTIFICATION_LIST"
        const val TAG_NOTIFICATION: String = "TAG_NOTIFICATION"
        const val TAG_FIRECHAT_BUTTON: String = "TAG_FIRECHAT_BUTTON"
        const val TAG_BUTTON_CLOSE: String = "TAG_BUTTON_CLOSE"
        const val TAG_BUTTON_DOWNLOAD: String = "TAG_BUTTON_DOWNLOAD"
    }
}