package com.minhtu.firesocialmedia.constants.home

class TestTag {
    companion object{
        const val TAG_ICON_BUTTON_SEARCH: String = "TAG_ICON_BUTTON_SEARCH"
        const val TAG_ICON_BUTTON_LOGOUT: String = "TAG_ICON_BUTTON_LOGOUT"
        const val TAG_CREATE_POST: String = "TAG_CREATE_POST"
        const val TAG_USERS_ROW: String = "TAG_USERS_ROW"
        const val TAG_ITEM_IN_ROW: String = "TAG_ITEM_IN_ROW"
        const val TAG_BUTTON_UPLOAD: String = "TAG_BUTTON_UPLOAD"
        const val TAG_BUTTON_SELECTIMAGE: String = "TAG_BUTTON_SELECTIMAGE"
        const val TAG_BUTTON_SELECTVIDEO: String = "TAG_BUTTON_SELECTVIDEO"
        const val TAG_BUTTON_POST: String = "TAG_BUTTON_POST"
        const val SCROLL_TO_TOP_BUTTON : String = "SCROLL_TO_TOP_BUTTON"
        const val TAG_BUTTON_DRAFTPOST : String = "TAG_BUTTON_DRAFTPOST"
        const val TAG_CURRENT_USER: String = "TAG_CURRENT_USER"
        const val TAG_BUTTON_ACCESS_MODIFIER: String = "TAG_BUTTON_ACCESS_MODIFIER"
        const val TAG_SELECT_PUBLIC: String = "TAG_SELECT_PUBLIC"
        const val TAG_SELECT_PRIVATE: String = "TAG_SELECT_PRIVATE"
        const val TAG_POST_IMAGE: String = "TAG_POST_IMAGE"
        const val TAG_BUTTON_DELETE: String = "TAG_BUTTON_DELETE"
        const val TAG_BUTTON_NO: String = "TAG_BUTTON_NO"
        const val TAG_POST_IN_COLUMN: String = "TAG_POST_IN_COLUMN"
        const val TAG_POSTER_AVATAR: String = "TAG_POSTER_AVATAR"
        const val TAG_POST_VIDEO: String = "TAG_POST_VIDEO"
        const val TAG_DRAFT: String = "TAG_DRAFT"
        const val TAG_POSTS_COLUMN: String = "TAG_POST_COLUMN"
        const val TAG_BUTTON_MOREOPTIONS: String = "TAG_BUTTON_MOREOPTIONS"
        const val TAG_POST_MESSAGE: String = "TAG_POST_MESSAGE"
        const val TAG_SHARE_APPS_ROW: String = "TAG_SHARE_APPS_ROW"
        const val TAG_BUTTON_LIKE: String = "TAG_BUTTON_LIKE"
        const val TAG_BUTTON_COMMENT: String = "TAG_BUTTON_COMMENT"
        const val TAG_BUTTON_SHARE: String = "TAG_BUTTON_SHARE"
        const val TAG_BUTTON_BACK: String = "TAG_BUTTON_BACK"
        const val TAG_BUTTON_CLOSE: String = "TAG_BUTTON_CLOSE"
    }
}
