source 'https://cdn.cocoapods.org'

target 'Fire_Social_Media' do
  use_frameworks! :linkage => :static
  platform :ios, '16.0'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'FirebaseStorage'
  pod 'FirebaseMessaging'
  pod 'core', :path => '../core'
  pod 'appInit', :path => '../appInit'
end