target 'Fire_Social_Media' do
  use_frameworks! :linkage => :static
  platform :ios, '16.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'shared', :path => '../shared'
end